### ISSUE TITLE
combine substitutions and diminutions?

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-OM#4]
May have covered this before, but is it possible to combine the r-substitute and r-diminutions objects into one object?  R-substitutions would be default and then mode 1 would be diminutions.  We would need to match the same functionality as you did in r-substitute to include a the single line interpreted as "global" and the multiple line for individual voices.

**Comment by equilet** [comment]
@mattschumaker if this is resolved, please close

**Comment by mattschumaker** [comment]
combine substitutions and diminutions? #4 : closed
